# Generated by Django 4.2.1 on 2023-05-13 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionInventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolutivo',
            name='devUbicacion',
            field=models.ForeignKey(db_comment='Hace relacion a la ubicacion FK', null=True, on_delete=django.db.models.deletion.PROTECT, to='appGestionInventario.ubicacionfisica'),
        ),
    ]
