# Generated by Django 4.2.1 on 2023-05-19 15:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionInventario', '0005_alter_detalleentradamaterial_devestado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='matUnidadMedida',
        ),
        migrations.AddField(
            model_name='detalleentradamaterial',
            name='detUnidadMedida',
            field=models.ForeignKey(db_comment='Hace referencia a la Unidad de Medida FK', default=None, on_delete=django.db.models.deletion.PROTECT, to='appGestionInventario.unidadmedida'),
        ),
        migrations.AlterField(
            model_name='entradamaterial',
            name='entFechaHora',
            field=models.DateTimeField(db_comment='Fecha y hora que entregan los elementos', default=datetime.datetime(2023, 5, 19, 15, 38, 5, 291038, tzinfo=datetime.timezone.utc)),
        ),
    ]
