# Generated by Django 4.2.1 on 2023-05-30 23:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionInventario', '0007_alter_entradamaterial_entfechahora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradamaterial',
            name='entFechaHora',
            field=models.DateTimeField(db_comment='Fecha y hora que entregan los elementos', default=datetime.datetime(2023, 5, 30, 23, 40, 3, 348888, tzinfo=datetime.timezone.utc)),
        ),
    ]
