# Generated by Django 4.2.1 on 2023-06-16 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionInventario', '0008_alter_entradamaterial_entfechahora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradamaterial',
            name='entFechaHora',
            field=models.DateTimeField(db_comment='Fecha y hora que entregan los elementos', default=datetime.datetime(2023, 6, 16, 11, 35, 1, 727566, tzinfo=datetime.timezone.utc)),
        ),
    ]
